/**
 * Galeria de ícones para o catálogo de disciplinas (client-safe).
 * São ícones lucide (portanto SVG), oferecidos ao admin ao cadastrar uma disciplina nova.
 * A chave (nome do ícone lucide) é o que fica salvo em `DisciplinaCatalogo.icone`.
 *
 * Disciplinas antigas continuam com o ícone derivado do nome (ver `lib/disciplinas.ts`);
 * esta galeria só entra quando o admin escolhe um ícone explicitamente.
 */
import {
  // Arquitetura / estrutura
  DraftingCompass,
  Frame,
  Building,
  Building2,
  Home,
  Ruler,
  PencilRuler,
  Layers,
  Shapes,
  Boxes,
  Blocks,
  Component,
  Landmark,
  // Elétrica
  Zap,
  Plug,
  PlugZap,
  Lightbulb,
  Cable,
  CircuitBoard,
  BatteryCharging,
  CloudLightning,
  UtilityPole,
  // Hidráulica
  Droplet,
  Droplets,
  Waves,
  ShowerHead,
  // Incêndio
  Flame,
  FireExtinguisher,
  Siren,
  // Mecânica / climatização
  AirVent,
  Fan,
  Wind,
  Thermometer,
  Snowflake,
  Gauge,
  Cylinder,
  Cog,
  Settings,
  Wrench,
  Hammer,
  HardHat,
  Construction,
  // Telecom / segurança
  Network,
  Wifi,
  Router,
  Antenna,
  Signal,
  Radio,
  Camera,
  Cctv,
  Shield,
  ShieldCheck,
  Lock,
  Bell,
  // Civil / terreno
  Mountain,
  MountainSnow,
  TreePine,
  Trees,
  Road,
  Route,
  TrafficCone,
  Truck,
  Tractor,
  Map,
  MapPin,
  Compass,
  Waypoints,
  // Diversos
  FlaskConical,
  AudioLines,
  Calculator,
  Sun,
  Package,
  ClipboardList,
  FileText,
  Brush,
  Box,
  type LucideIcon,
} from "lucide-react";

export const GALERIA_ICONES: Record<string, LucideIcon> = {
  DraftingCompass,
  Frame,
  Building,
  Building2,
  Home,
  Ruler,
  PencilRuler,
  Layers,
  Shapes,
  Boxes,
  Blocks,
  Component,
  Landmark,
  Zap,
  Plug,
  PlugZap,
  Lightbulb,
  Cable,
  CircuitBoard,
  BatteryCharging,
  CloudLightning,
  UtilityPole,
  Droplet,
  Droplets,
  Waves,
  ShowerHead,
  Flame,
  FireExtinguisher,
  Siren,
  AirVent,
  Fan,
  Wind,
  Thermometer,
  Snowflake,
  Gauge,
  Cylinder,
  Cog,
  Settings,
  Wrench,
  Hammer,
  HardHat,
  Construction,
  Network,
  Wifi,
  Router,
  Antenna,
  Signal,
  Radio,
  Camera,
  Cctv,
  Shield,
  ShieldCheck,
  Lock,
  Bell,
  Mountain,
  MountainSnow,
  TreePine,
  Trees,
  Road,
  Route,
  TrafficCone,
  Truck,
  Tractor,
  Map,
  MapPin,
  Compass,
  Waypoints,
  FlaskConical,
  AudioLines,
  Calculator,
  Sun,
  Package,
  ClipboardList,
  FileText,
  Brush,
  Box,
};

/** Lista ordenada de chaves da galeria (para renderizar o picker). */
export const CHAVES_GALERIA = Object.keys(GALERIA_ICONES);

/** Componente do ícone pela chave da galeria (ou `undefined` se a chave não existir). */
export function iconeDaGaleria(chave: string | null | undefined): LucideIcon | undefined {
  return chave ? GALERIA_ICONES[chave] : undefined;
}
