/**
 * Traduções legíveis (pt-BR) para as ações técnicas registradas em AuditLog.
 * As chaves correspondem ao campo `acao` das server actions (src/modules/**\/actions.ts).
 * Use sempre com fallback para a própria ação: ACAO_LABEL[acao] ?? acao.
 */
export const ACAO_LABEL: Record<string, string> = {
  // Acesso / sistema
  "trocar-senha": "Trocou a senha",
  "solicitar-reset-senha": "Solicitou redefinição de senha",
  "resetar-senha-usuario": "Redefiniu senha de usuário",
  "salvar-senha-exclusao": "Definiu senha de exclusão",
  "set-permissao": "Alterou permissão",
  "salvar-preferencia": "Salvou preferência",

  // Usuários
  "criar-usuario": "Criou usuário",
  "editar-usuario": "Editou usuário",
  "desativar-usuario": "Desativou usuário",
  "reativar-usuario": "Reativou usuário",
  "avaliar-solicitacao-cadastro": "Avaliou solicitação de cadastro",

  // Agenda
  "criar-compromisso": "Criou compromisso",
  "editar-compromisso": "Editou compromisso",
  "excluir-compromisso": "Excluiu compromisso",
  "confirmar-presenca": "Confirmou presença",

  // Documentos
  "criar-modelo": "Criou modelo de documento",
  "salvar-modelo": "Salvou modelo de documento",
  "duplicar-modelo": "Duplicou modelo de documento",
  "arquivar-modelo": "Arquivou modelo de documento",
  "editar-modelo": "Editou modelo de documento",
  "excluir-modelo": "Excluiu modelo de documento",
  "restaurar-versao": "Restaurou versão",
  "salvar-padrao-doc": "Salvou padrão de documento",
  "gerar-documento": "Gerou documento",
  "criar-pasta": "Criou pasta",
  "renomear-pasta": "Renomeou pasta",
  "excluir-pasta": "Excluiu pasta",
  "criar-arquivo": "Criou arquivo",
  "editar-arquivo": "Editou arquivo",
  "excluir-arquivo": "Moveu arquivo para a lixeira",
  "excluir-arquivos-lote": "Moveu arquivos para a lixeira (em lote)",
  "restaurar-arquivo": "Restaurou arquivo da lixeira",
  "excluir-arquivo-definitivo": "Excluiu arquivo em definitivo",
  "adicionar-versao-arquivo": "Adicionou versão de arquivo",
  "criar-doc": "Criou documento",
  "excluir-doc": "Excluiu documento",
  "mover-doc-pasta": "Moveu documento de pasta",

  // Financeiro
  "criar-conta": "Criou conta",
  "editar-conta": "Editou conta",
  "criar-categoria": "Criou categoria",
  "editar-categoria": "Editou categoria",
  "criar-centro": "Criou centro de custo",
  "editar-centro": "Editou centro de custo",
  "criar-forma": "Criou forma de pagamento",
  "editar-forma": "Editou forma de pagamento",
  "criar-lancamento": "Criou lançamento",
  "editar-lancamento": "Editou lançamento",
  "excluir-lancamento": "Excluiu lançamento",
  "cancelar-lancamento": "Cancelou lançamento",
  "confirmar-lancamento": "Confirmou lançamento",
  "aprovar-lancamento": "Aprovou lançamento",
  "rejeitar-lancamento": "Rejeitou lançamento",
  "baixar-lancamentos-lote": "Deu baixa em lançamentos (lote)",
  "criar-lancamento-transacao": "Criou lançamento a partir de transação",
  "conciliar-transacao": "Conciliou transação",
  "ignorar-transacao": "Ignorou transação",
  "classificar-dfc": "Classificou no DFC",
  "add-anexo-lancamento": "Adicionou anexo ao lançamento",
  "rm-anexo-lancamento": "Removeu anexo do lançamento",
  "salvar-tags-lancamento": "Salvou tags do lançamento",
  "criar-doc-financeiro": "Criou documento financeiro",
  "excluir-doc-financeiro": "Excluiu documento financeiro",
  "gerar-parcelas-doc": "Gerou parcelas do documento",
  "criar-plano-pagamento": "Criou plano de pagamento",
  "atualizar-plano-pagamento": "Atualizou plano de pagamento",
  "excluir-plano-pagamento": "Excluiu plano de pagamento",
  "executar-plano-pagamento": "Executou plano de pagamento",
  "mudar-status-plano": "Alterou status do plano",
  "importar-financeiro": "Importou dados financeiros",
  "validar-importacao": "Validou importação",
  "desfazer-importacao": "Desfez importação",
  "fechar-mes": "Fechou o mês",
  "fechar-rateio": "Fechou rateio",
  "salvar-config-financeiro": "Salvou configuração financeira",
  "salvar-limite-aprovacao": "Salvou limite de aprovação",
  "salvar-niveis-aprovacao": "Salvou níveis de aprovação",
  "validar-nf": "Validou nota fiscal",

  // RH / Folha / Ponto
  "criar-folha": "Criou folha de pagamento",
  "gerar-folha-lote": "Gerou folha em lote",
  "fechar-folha": "Fechou folha de pagamento",
  "reabrir-folha": "Reabriu folha de pagamento",
  "salvar-holerite": "Salvou holerite",
  "remover-holerite": "Removeu holerite",
  "gerar-holerites-auto": "Gerou holerites automaticamente",
  "enviar-holerites": "Enviou holerites",
  "salvar-salario": "Salvou salário",
  "salvar-admissao": "Registrou admissão",
  "salvar-aliquotas": "Salvou alíquotas",
  "salvar-faixas-encargo": "Salvou faixas de encargo",
  "salvar-deducao-dep": "Salvou dedução de dependente",
  "add-dependente": "Adicionou dependente",
  "rm-dependente": "Removeu dependente",
  "add-doc-funcionario": "Adicionou documento do funcionário",
  "rm-doc-funcionario": "Removeu documento do funcionário",
  "bater-ponto": "Bateu ponto",
  "registrar-ponto-manual": "Registrou ponto manual",
  "encerrar-jornada": "Encerrou jornada",
  "fechar-banco-horas": "Fechou banco de horas",
  "definir-escala": "Definiu escala",
  "solicitar-ferias": "Solicitou férias",
  "validar-ferias": "Validou férias",
  "validar-abono": "Validou abono",
  "gerar-fechamento": "Gerou fechamento",
  "excluir-fechamento": "Excluiu fechamento",
  "reabrir-fechamento": "Reabriu fechamento",
  "importar-feriados": "Importou feriados",
  "salvar-feriado": "Salvou feriado",
  "excluir-feriado": "Excluiu feriado",

  // Projetos / EAP / Tarefas
  "criar-projeto": "Criou projeto",
  "editar-projeto": "Editou projeto",
  "trocar-projeto": "Trocou de projeto",
  "criar-eap": "Criou EAP",
  "editar-eap": "Editou EAP",
  "excluir-eap": "Excluiu EAP",
  "criar-tarefa": "Criou tarefa",
  "editar-tarefa": "Editou tarefa",
  "arquivar-tarefa": "Arquivou tarefa",
  "mover-tarefa": "Moveu tarefa",
  "comentar-tarefa": "Comentou na tarefa",
  "rm-comentario-tarefa": "Removeu comentário da tarefa",
  "toggle-item-tarefa": "Marcou item da tarefa",
  "definir-linha-base": "Definiu linha de base",
  "salvar-linha-base": "Salvou linha de base",
  "excluir-linha-base": "Excluiu linha de base",
  "registrar-medicao": "Registrou medição",
  "excluir-medicao": "Excluiu medição",
  "salvar-alocacao": "Salvou alocação",
  "remover-alocacao": "Removeu alocação",
  "atualizar-status-disciplina": "Atualizou status da disciplina",
  "criar-prancha": "Criou prancha",
  "editar-prancha": "Editou prancha",
  "excluir-prancha": "Excluiu prancha",
  "solicitar-revisao": "Solicitou revisão",
  "responder-revisao": "Respondeu revisão",
  "registrar-revisao": "Registrou revisão",
  "definir-responsaveis": "Definiu responsáveis",
  "definir-membros": "Definiu membros",
  "definir-meta": "Definiu meta",

  // CRM / Leads / Oportunidades
  "criar-lead": "Criou lead",
  "editar-lead": "Editou lead",
  "mover-lead": "Moveu lead",
  "arquivar-lead": "Arquivou lead",
  "converter-lead": "Converteu lead",
  "nota-lead": "Adicionou nota ao lead",
  "criar-oportunidade": "Criou oportunidade",
  "atualizar-oportunidade": "Atualizou oportunidade",
  "excluir-oportunidade": "Excluiu oportunidade",
  "registrar-atividade-op": "Registrou atividade da oportunidade",
  "criar-cliente": "Criou cliente",
  "editar-cliente": "Editou cliente",
  "desativar-cliente": "Desativou cliente",
  "reativar-cliente": "Reativou cliente",
  "criar-proposta": "Criou proposta",
  "salvar-proposta": "Salvou proposta",
  "copiar-proposta": "Copiou proposta",
  "status-proposta": "Alterou status da proposta",
  "enviar-proposta-email": "Enviou proposta por e-mail",
  "aceitar-proposta": "Aceitou proposta",
  "add-anexo-proposta": "Adicionou anexo à proposta",
  "rm-anexo-proposta": "Removeu anexo da proposta",

  // Licitações
  "criar-licitacao": "Criou licitação",
  "editar-licitacao": "Editou licitação",
  "excluir-licitacao": "Excluiu licitação",
  "importar-licitacao": "Importou licitação",
  "criar-evento-licitacao": "Criou evento da licitação",
  "editar-evento-licitacao": "Editou evento da licitação",
  "excluir-evento-licitacao": "Excluiu evento da licitação",
  "registrar-evento-licitacao": "Registrou evento da licitação",
  "concluir-evento-licitacao": "Concluiu evento da licitação",
  "salvar-viabilidade": "Salvou viabilidade",
  "decidir-viabilidade": "Decidiu viabilidade",
  "salvar-rt": "Salvou responsável técnico",
  "excluir-rt": "Excluiu responsável técnico",
  "vincular-rt": "Vinculou responsável técnico",
  "desvincular-rt": "Desvinculou responsável técnico",
  "salvar-composicao-licitacao": "Salvou composição da licitação",
  "salvar-contrato-licitacao": "Salvou contrato da licitação",
  "salvar-resultado-licitacao": "Salvou resultado da licitação",
  "adicionar-aditivo-contrato": "Adicionou aditivo de contrato",
  "remover-aditivo-contrato": "Removeu aditivo de contrato",
  "salvar-habilitacao": "Salvou habilitação",
  "semear-habilitacao": "Gerou itens de habilitação",
  "salvar-sancao-propria": "Salvou sanção própria",
  "excluir-sancao-propria": "Excluiu sanção própria",
  "salvar-sancao-concorrente": "Salvou sanção de concorrente",
  "excluir-sancao-concorrente": "Excluiu sanção de concorrente",
  "salvar-config-licitacoes": "Salvou configuração de licitações",
  "salvar-modalidade": "Salvou modalidade",
  "excluir-modalidade": "Excluiu modalidade",
  "alternar-modalidade": "Alternou modalidade",
  "restaurar-modalidades": "Restaurou modalidades",
  "salvar-dados-pncp": "Salvou dados do PNCP",
  "marcar-publicado-pncp": "Marcou como publicado no PNCP",
  "salvar-valor-disc-licitacao": "Salvou valor de disciplina",
  "remover-valor-disc-licitacao": "Removeu valor de disciplina",
  "excluir-versao-doc-licitacao": "Excluiu versão de documento",
  "salvar-recurso": "Salvou recurso",
  "salvar-orcamento-item": "Salvou item de orçamento",

  // Fornecedores / Serviços / Tabelas
  "criar-fornecedor": "Criou fornecedor",
  "editar-fornecedor": "Editou fornecedor",
  "criar-forn-servico": "Criou serviço de fornecedor",
  "remover-forn-servico": "Removeu serviço de fornecedor",
  "alternar-fornecedor": "Alternou fornecedor",
  "criar-servico": "Criou serviço",
  "editar-servico": "Editou serviço",
  "excluir-servico": "Excluiu serviço",
  "criar-tabela-preco": "Criou tabela de preço",
  "editar-tabela-preco": "Editou tabela de preço",
  "salvar-composicao": "Salvou composição",
  "criar-certidao": "Criou certidão",
  "excluir-certidao": "Excluiu certidão",
  "nova-versao-certidao": "Adicionou versão de certidão",

  // Sócios
  "criar-socio": "Criou sócio",
  "editar-socio": "Editou sócio",
  "remover-socio": "Removeu sócio",
  "criar-retirada-socio": "Registrou retirada de sócio",
  "remover-retirada-socio": "Removeu retirada de sócio",

  // Chat / Mensagens / Tickets / Suporte
  "enviar-mensagem": "Enviou mensagem",
  "abrir-dm": "Abriu conversa direta",
  "fixar-mensagem": "Fixou mensagem",
  "status-chat": "Alterou status do chat",
  "abrir-ticket": "Abriu ticket",
  "responder-ticket": "Respondeu ticket",
  "status-ticket": "Alterou status do ticket",
  "aviso-geral": "Publicou aviso geral",
  "criar-aviso": "Enviou aviso geral",
  "salvar-email-variante": "Salvou modelo de e-mail",
  "ativar-email-variante": "Ativou/desativou modelo de e-mail",
  "excluir-email-variante": "Excluiu modelo de e-mail",
  "enviar-email-teste": "Enviou e-mail de teste",
  "registrar-humor": "Registrou humor",
  "registrar-feedback": "Registrou feedback",
  "remover-feedback": "Removeu feedback",

  // Onboarding / Habilidades
  "criar-onboarding": "Criou onboarding",
  "remover-onboarding": "Removeu onboarding",
  "toggle-onboarding-item": "Marcou item de onboarding",
  "criar-habilidade": "Criou habilidade",
  "excluir-habilidade": "Excluiu habilidade",
  "toggle-habilidade": "Alternou habilidade",

  // Inputs / Templates
  "criar-input-template": "Criou template de input",
  "editar-input-template": "Editou template de input",
  "excluir-input-template": "Excluiu template de input",
  "adicionar-input": "Adicionou input",
  "remover-input": "Removeu input",
  "aplicar-inputs-padrao": "Aplicou inputs padrão",
  "gerar-link-input": "Gerou link de input",
  "responder-inputs": "Respondeu inputs",

  // Planos / Orçamento
  "adicionar-linhas-plano": "Adicionou linhas ao plano",
  "remover-linha-plano": "Removeu linha do plano",
  "salvar-linhas-plano": "Salvou linhas do plano",
  "aplicar-plano": "Aplicou plano",
};

/** Rótulos legíveis (pt-BR) para os módulos/seções registrados em AuditLog.modulo. */
export const MODULO_LABEL: Record<string, string> = {
  inicio: "Início",
  auth: "Autenticação",
  usuarios: "Usuários",
  permissoes: "Permissões",
  clientes: "Clientes",
  comercial: "Comercial",
  projetos: "Projetos",
  planejamento: "Planejamento",
  tarefas: "Tarefas",
  agenda: "Agenda",
  financeiro: "Financeiro",
  rh: "RH",
  ponto: "Ponto",
  chat: "Chat",
  documentos: "Documentos",
  qualidade: "Qualidade",
  licitacoes: "Licitações",
  juridico: "Jurídico",
  suporte: "Suporte",
  notificacoes: "Notificações",
  uploads: "Uploads",
  portal: "Portal do cliente",
  inputs: "Inputs",
  busca: "Busca",
  dashboard: "Dashboard",
  ferramentas: "Ferramentas",
};

export function moduloLabel(modulo: string): string {
  return MODULO_LABEL[modulo] ?? modulo.charAt(0).toUpperCase() + modulo.slice(1);
}
